version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/node:14.5
    working_directory: ~/ci_app

orbs:
  sfdx: circleci/salesforce-sfdx@2.1
jobs:
  static-analysis: 
    docker:
      - image: circleci/openjdk:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - pmd-v6.0.1
      - run:
          name: Install PMD
          command: |
              if [ ! -d pmd-bin-6.0.1 ]; then
                  curl -L "https://github.com/pmd/pmd/releases/download/pmd_releases/6.0.1/pmd-bin-6.0.1.zip" -o pmd-bin-6.0.1.zip
                  unzip pmd-bin-6.0.1.zip
                  rm pmd-bin-6.0.1.zip
              fi
      - save_cache:
          key: pmd-v6.0.1
          paths:
              - pmd-bin-6.0.1
      - run:
          name: Run Static Analysis
          command: |
              pmd-bin-6.0.1/bin/run.sh pmd -d . -R apex_ruleset.xml -f text -l apex -r static-analysis.txt
      - store_artifacts:
          path: static-analysis.txt
  TestDeployShared:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth Shared
          command: . ~/ci_app/ciScripts/authShared.sh
      - run:
          name: Test Shared Deployment
          command: |
            sfdx force:source:deploy -p force-app -u shared -l RunLocalTests -w 33 --loglevel info --checkonly
  DeployToShared:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth Shared
          command: . ~/ci_app/ciScripts/authShared.sh
      - run:
          name: Shared Deployment
          command: |
            sfdx force:source:deploy -p force-app -u shared -l RunLocalTests -w 33 --loglevel info
  TestDeployUAT:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth UAT
          command: . ~/ci_app/ciScripts/authUAT.sh
      - run:
          name: Test UAT Deployment
          command: |
            sfdx force:source:deploy -p force-app -u uat -l RunLocalTests -w 33 --loglevel info --checkonly
  DeployToUAT:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth UAT
          command: . ~/ci_app/ciScripts/authUAT.sh
      - run:
          name: UAT Deployment
          command: |
            sfdx force:source:deploy -p force-app -u uat -l RunLocalTests -w 33 --loglevel info
  TestDeployProd:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth Prod
          command: . ~/ci_app/ciScripts/authProd.sh
      - run:
          name: Test Production Deployment
          command: |
            sfdx force:source:deploy -p force-app -u prod -l RunLocalTests -w 33 --loglevel info --checkonly
  DeployToProd:
    executor: my-executor
    steps:
      - sfdx/install
      - checkout
      - run:
          name: Auth Prod
          command: . ~/ci_app/ciScripts/authProd.sh
      - run:
          name: Production Deployment
          command: |
            sfdx force:source:deploy -p force-app -u prod -l RunLocalTests -w 33 --loglevel info
workflows:
  Tests:
    jobs:
      - static-analysis
      - TestDeployUAT:
          name: Test Deployment to UAT
          filters:
            branches:
              only:
                - /^(?i)Feature.*/
                - /^(?i)Hotfix.*/
      - TestDeployProd:
          name: Test Deployment to Prod
          filters:
            branches:
              only:
                - /^(?i)Deploy-Prod.*/
                - /^(?i)Prod-Deploy.*/
                - /^(?i)Release.*/
                - /^(?i)Hotfix.*/
  Deploys:
    jobs:
      - static-analysis
      - DeployToUAT:
          name: Deployment to UAT
          filters:
            branches:
              only:
                - /^(?i)master/
                - /^(?i)Dev/
                - /^(?i)Development/
      - DeployToProd:
          name: Deployment to Production
          filters:
            branches:
              only:
                - /^(?i)Prod/
